const cards = [
  { nr: 1, category: "AUFWÄRMEN", title: "Sanfter Beginn", instruction: "Langsam und gleichmäßig. Nur Fingerspitzen, kein Druck. 20 Sekunden." },
  { nr: 2, category: "AUFWÄRMEN", title: "Atemzug für Atemzug", instruction: "Atme tief. Bei jedem Ausatmen ein langsamer Streichelzug. 10 Wiederholungen." },
  { nr: 3, category: "AUFWÄRMEN", title: "Kreisen", instruction: "Mit der flachen Hand oder Fingerspitzen kreisförmig um die Eichel. 20 Sekunden." },
  { nr: 4, category: "AUFWÄRMEN", title: "Randzonen", instruction: "Nur Schaft, keine Eichel. 30 Sekunden in einem gleichmäßigen Tempo." },
  { nr: 5, category: "AUFWÄRMEN", title: "Luftkontakt", instruction: "Nur mit Abstand: streiche über den Schaft, ohne ihn fest zu berühren. Max. 30 Sekunden." },
  { nr: 6, category: "AUFWÄRMEN", title: "Sanft am Rand", instruction: "Nur Fingerspitzen, nur an der Peniswurzel. Keine Eichel, kein Schaft. 20 Sekunden." },
  { nr: 7, category: "AUFWÄRMEN", title: "Gleichmäßig ziehen", instruction: "Langsam ziehen vom Ansatz bis zur Eichel. Jede Runde 5 Sekunden. Fünf Wiederholungen." },
  { nr: 8, category: "AUFWÄRMEN", title: "Kontaktlinien", instruction: "Nur mit zwei Fingern den Schaft entlanggleiten. Kein Umgreifen. 20 Sekunden." },
  { nr: 9, category: "AUFWÄRMEN", title: "Halbe Hand", instruction: "Nur mit Daumen und Zeigefinger – ohne Druck, ohne Tempo. 30 Sekunden." },
  { nr: 10, category: "AUFWÄRMEN", title: "Grifflos", instruction: "Handfläche anlegen, leichtes Schieben statt Umgreifen. Fühlen, nicht greifen. 20 Sekunden." },
  { nr: 11, category: "KONTROLLE", title: "Fünf und Schluss", instruction: "Fünf schnelle Bewegungen, dann 10 Sekunden Pause. Wiederhole fünfmal." },
  { nr: 12, category: "KONTROLLE", title: "3-2-1", instruction: "Drei Sekunden schnell, zwei Sekunden langsam, eine Sekunde gar nicht. Wiederhole." },
  { nr: 13, category: "KONTROLLE", title: "Kneten", instruction: "Abwechselnd fest und locker kneten. 20 Sekunden." },
  { nr: 14, category: "KONTROLLE", title: "Mit Druck", instruction: "Umfasse den Penis etwas fester. Schnell auf und ab. 30 Sekunden." },
  { nr: 15, category: "KONTROLLE", title: "Mit Druck", instruction: "Umfasse den Penis etwas fester. Langsam auf und ab. 30 Sekunden." },
  { nr: 16, category: "KONTROLLE", title: "Stopp & Griffwechsel", instruction: "Sobald es intensiv wird, sofort stoppen und Griff ändern. 3× in Folge." },
  { nr: 17, category: "KONTROLLE", title: "Präzisionspause", instruction: "Stimulation beginnt, endet und startet exakt mit einem Atemzug. 5 Wiederholungen." },
  { nr: 18, category: "KONTROLLE", title: "Triggerkontrolle", instruction: "Spüre, wann der Impuls zum Kommen auftritt. Stoppe exakt dort. 15 Sekunden unten Halten." },
  { nr: 19, category: "KONTROLLE", title: "Kantenwechsel", instruction: "Stimulation an Schaftseite links – 10 Sekunden. Dann rechts. Dann wieder links. 3×." },
  { nr: 20, category: "KONTROLLE", title: "Sekundentakt", instruction: "2 Sekunden Bewegung, 2 Sekunde Pause. Im Wechsel für 1 Minute." },
  { nr: 21, category: "SPIEL & EROTIK", title: "Nur schauen", instruction: "Halte den Penis unten fest und schaue ihn dir genau an. 20 Sekunden." },
  { nr: 22, category: "SPIEL & EROTIK", title: "Er bestimmt", instruction: "Er wählt Griff & Tempo. Du führst nur aus. 60 Sekunden." },
  { nr: 23, category: "SPIEL & EROTIK", title: "Lieblingsgriff", instruction: "Nutze deine bevorzugte Technik – aber langsamer als gewohnt. 30 Sekunden." },
  { nr: 24, category: "SPIEL & EROTIK", title: "Lieblingsgriff", instruction: "Nutze deine bevorzugte Technik – aber schneller als gewohnt. 30 Sekunden." },
  { nr: 25, category: "SPIEL & EROTIK", title: "Unten anfangen", instruction: "Starte an der Wurzel. Wandere langsam nach oben. Wieder runter. 3× wiederholen." },
  { nr: 26, category: "SPIEL & EROTIK", title: "Wechselspiel", instruction: "5 Sekunden schnell, 5 Sekunden langsam. Wiederhole sechsmal." },
  { nr: 27, category: "SPIEL & EROTIK", title: "Flüsterton", instruction: "Flüstere deinem Partner zu, was du tust – während du es tust. 60 Sekunden." },
  { nr: 28, category: "SPIEL & EROTIK", title: "Bevorzugt verboten", instruction: "Streichle genau so, wie du weißt, dass es „zu gut“ ist. Aber nur für 20 Sekunden. Danach: absolute Ruhe." },
  { nr: 29, category: "SPIEL & EROTIK", title: "Schnell-Langsam-Halten", instruction: "5x schnell, dann in 10 Sekunden langsamer werden bis zum Stillstand, dann 5 Sekunden unten halten." },
  { nr: 30, category: "SPIEL & EROTIK", title: "Sprechen", instruction: "Sprich laut aus, was du tust – in kurzen Sätzen. 30 Sekunden." },
  { nr: 31, category: "SPIEL & EROTIK", title: "Langsames Kino", instruction: "Jede Bewegung so führen, als würde sie in Zeitlupe aufgenommen. 30 Sekunden." },
  { nr: 32, category: "SPIEL & EROTIK", title: "Befehlston", instruction: "Du gibst dir selbst laut Kommandos: „Start“, „Stopp“, „Schneller“. 1 Minute." },
  { nr: 33, category: "SPIEL & EROTIK", title: "Erlaubnis holen", instruction: "Sie macht: Er vor jeder Bewegung ansagen: „schnell / langsam / Rythmus“ – dann erst ausführen. 5×." },
  { nr: 34, category: "SPIEL & EROTIK", title: "Erlaubnis holen", instruction: "Er macht: Sie vor jeder Bewegung ansagen: „schnell / langsam / Rythmus“ – dann erst ausführen. 5×." },
  { nr: 35, category: "STEIGERUNG", title: "Langzeitimpuls", instruction: "30 Sekunden durchgehende, exakt gleiche Bewegung – keinerlei Änderung." },
  { nr: 36, category: "STEIGERUNG", title: "Warten lohnt", instruction: "10 Sekunden nichts. Dann 10 Sekunden sehr intensiv. Wiederhole dreimal." },
  { nr: 37, category: "STEIGERUNG", title: "Taktgeber", instruction: "Staccato-Stimulation. Kurze, schnelle Impulse – jeweils 3 Sekunden. Dann 3 Sekunden Pause. 10 Wiederholungen." },
  { nr: 38, category: "STEIGERUNG", title: "Langsam–Schnell–Stopp", instruction: "Fünf Sekunden langsam, fünf schnell, dann 5 Sekunden Pause. Wiederhole." },
  { nr: 39, category: "STEIGERUNG", title: "10 Sekunden High-Speed", instruction: "So schnell wie möglich – 10 Sekunden lang. Dann 15 Sekunden Pause. Wiederhole." },
  { nr: 40, category: "STEIGERUNG", title: "Druck aufbauen", instruction: "Beginn mit leichtem Griff, steigere jede 10 Sekunden den Druck. 60 Sekunden insgesamt." },
  { nr: 41, category: "STEIGERUNG", title: "Eichelfokus", instruction: "Nur die Eichel. Kleine, kreisende Bewegungen. 30 Sekunden." },
  { nr: 42, category: "STEIGERUNG", title: "Countdown-Edge", instruction: "Zähle langsam von 6 auf 1 – bei jeder Zahl ein Griff- oder Geschwindigkeitswechsel." },
  { nr: 43, category: "STEIGERUNG", title: "Doppelschlag", instruction: "Zwei schnelle, ein langsamer Zug – im Takt. Wiederhole 10 Mal." },
  { nr: 44, category: "STEIGERUNG", title: "Zentimeterweise", instruction: "Arbeite dich Zentimeter für Zentimeter am Schaft entlang – rauf und runter. 2x" },
  { nr: 45, category: "STEIGERUNG", title: "Halbe Strecke", instruction: "Nur bis zur Schaftmitte, dann zurück. Rhythmisch, gleichmäßig. 60 Sekunden." },
  { nr: 46, category: "STEIGERUNG", title: "Rückwärtsgang", instruction: "Streicheln: von Eichel zur Wurzel gleiten, dann oben wieder ansetzen. 20 Sekunden durchgehend." },
  { nr: 47, category: "STEIGERUNG", title: "Schneller Wechsel", instruction: "5 Sekunden langsam, dann sofort 5 Sekunden schnell. 6 Wiederholungen." },
  { nr: 48, category: "STEIGERUNG", title: "Haltepunkte", instruction: "Stimulation in 10-Sekunden-Blöcken. Jeweils mit 5 Sekunden Pause. Insgesamt 1 Minute." },
  { nr: 49, category: "STEIGERUNG", title: "Grifftreppe", instruction: "Start: sanfter Griff. Alle 10 Sekunden leicht fester. Nach 50 Sekunden: loslassen." },
  { nr: 50, category: "STEIGERUNG", title: "Taktgeber", instruction: "Zähle im Kopf: „Eins – Zwei – Drei – Pause“. Jeder Takt ist ein Streichelzyklus. 5 Wiederholungen." },
  { nr: 51, category: "STEIGERUNG", title: "Reizschub", instruction: "Stimulation schnell beginnen und langsamer werden. Am Ende für 5 Sekunden unten halten." },
  { nr: 52, category: "STEIGERUNG", title: "Reizschub", instruction: "Stimulation langsam beginnen und schneller werden. Am Ende für 5 Sekunden Tempo verdoppeln." },
  { nr: 53, category: "STEIGERUNG", title: "Nur aufwärts", instruction: "Streichel nur vom Ansatz nach oben. Kein Rückweg. 20 Sekunden." },
  { nr: 54, category: "STEIGERUNG", title: "Richtungswechsel", instruction: "Wechsle alle 10 Sekunden die Richtung: hoch – runter – hoch … 6 Wiederholungen." },
  { nr: 55, category: "STEIGERUNG", title: "Griffrotation", instruction: "Stimulation mit drehendem Handgelenk, nicht nur auf/ab. 30 Sekunden." },
  { nr: 56, category: "STEIGERUNG", title: "Randzone 2.0", instruction: "Nur den Übergang: Schaft zu Eichel. Kein direktes Berühren der Eichel. 45 Sekunden." },
  { nr: 57, category: "STEIGERUNG", title: "Doppelpuls", instruction: "Zwei kurze Bewegungen, dann kurze Pause. Wiederholen – 30 Sekunden." },
  { nr: 58, category: "STEIGERUNG", title: "Fester Abschluss", instruction: "Letzte 10 Sekunden: fest, schnell, kontrolliert. Danach sofort loslassen." },
  { nr: 59, category: "STEIGERUNG", title: "Handruhe", instruction: "Nur Bewegung aus dem Arm, nicht aus der Hand. Kontrolliert, gleichmäßig, 30 Sekunden." },
  { nr: 60, category: "STEIGERUNG", title: "Konsequenzmodus", instruction: "JOKER: 30 Sekunden freie Bewegung. Danach: keine Diskussion. Sofort Hände weg." },
  { nr: 61, category: "MACHT & BELONUNG", title: "Edgepunkt halten", instruction: "Geh nah an die Kante, dann Stopp. Halte den Impuls aus, ohne loszulassen. 30 Sekunden." },
  { nr: 62, category: "MACHT & BELONUNG", title: "3× fast kommen", instruction: "Stimulation bis kurz davor. Stoppen. Wiederholen. Dreimal. Kein Höhepunkt." },
  { nr: 63, category: "MACHT & BELONUNG", title: "Belohnung auf Zeit", instruction: "60 Sekunden frei wählbare Stimulation – aber nur im unteren oder oberen Tempo." },
  { nr: 64, category: "MACHT & BELONUNG", title: "Kontrolle behalten", instruction: "Stimulation, aber kein Höhepunkt – egal wie nah du bist. Beweise deine Disziplin." },
  { nr: 65, category: "MACHT & BELONUNG", title: "Nur mit Befehl", instruction: "Gib dir selbst laut den Befehl zum Start. Danach 30 Sekunden durchziehen." },
  { nr: 66, category: "MACHT & BELONUNG", title: "Der letzte Zug", instruction: "Wähle eine Bewegung, die du als „final“ empfindest – führe sie aus, aber stoppe direkt danach." },
  { nr: 67, category: "MACHT & BELONUNG", title: "Harter Cut", instruction: "Stimulation abbrechen – genau mitten im besten Moment. Nur beobachten, nicht berühren. 2x" },
  { nr: 68, category: "MACHT & BELONUNG", title: "Abschluss auf Ansage", instruction: "Er macht: Sprich laut: „Stopp.“ – er beendet die Bewegung augenblicklich. Kein Nachgleiten. Kein Zögern." },
];
